### ISSUE TITLE
Clarify cardinality of EHR Responses

### ISSUE THREAD

**Issue by dennispatterson** [smart-on-fhir/smart-web-messaging#1]
Had some good discussion with @bkaney at the May HL7 Connectathon in Montreal about the cardinality of EHR Responses.  That is, if a client sends an EHR a message, is the expectation that the EHR should only return one reply?  Or, can two replies come back with the same "responseToMessageId"?

Because the statuses of these replies are modeled after http statuses, it's somewhat implied that there is one reply, but theoretically an EHR could choose to return a 202 initially and then a 200/201 at completion.

**Comment by bkaney** [comment]
The implementation I put together here https://github.com/Vermonster/fhir-kit-client/pull/100 assumes that there could be one-to-many. 

After thinking about this more, I'm not sure we ought be constrained by (or force) a request-response pattern here...

**Comment by isaacvetter** [comment]
Overall, it would be easier and more understandable and simpler to define a single response for a request.

**Comment by bkaney** [comment]
> Brian, was there a specific use-case that made this clearly necessary?

Two things: 1) I don't know enough to rule out supporting multiple messages (from the EHR) with the same `responseToMessageId` and 2) being built on an async protocol, it feels strange to force it to a request-response pattern.

A hypothetical use-case could be an expensive or enqueued operation where status might be messaged back to the SMART app as it is processed.

**Comment by pcurc** [comment]
Could there also be a case where one message contains multiple requests, leading to the EHR responding to them independently?

e.g. SMART app sends message "prepare orders for the following drugs in the scratchpad: [drug1, drug2, drug3 ...]"; EHR responds with multiple messages (with the same `responseToMessageId`) corresponding to the outcome of preparing each order individually?

**Comment by brettmarquard** [comment]
Discussed on 5/31 Argonaut PAMA call - planning to proceed with a request/response paradigm until a specific scenario arises that requires multiple messages.
